### ISSUE TITLE
@k19051 @LongMine 追加時も削除時と同様にソート状態の保持を実装してください

### ISSUE THREAD

**Issue by Lium1126** [2020-AIT-OOP2-Group10/BubbleToDo#18]
実装作業は主に@LongMineがするようお願いします。ソート状態を保持する機能について、詳しくは@k19051が分かっているので、相談しつつ進めてください。

**Comment by Shiono-k19051** [comment]
ソートしてあるかソートしていないかはindex.htmlの中の61行目(ソートボタン)のvalueの中身を見ると分かります。
　→ソートしてあると、sorted
　→ソートしてないと、init(初期状態はこっち)

　この値をdocument.getElementById("sort-submit”)で取得して、
　→ソートしてあると、init(app_route="/sort")
　→ソートしてないと、init()

　を行ってください。
　(main.jsの90~94行目に削除版のコードがあります)

**Comment by LongMine** [comment]
了解です。ありがとうございます。
