### ISSUE TITLE
@LongMine IDの重複を回避するようにしてください

### ISSUE THREAD

**Issue by Lium1126** [2020-AIT-OOP2-Group10/BubbleToDo#29]
現状では新規データのIDが「現在登録されているデータ数+1」となっていますが、IDの重複が発生してしまう場合があります。IDの重複を避けるよう実装し直してください。

**Comment by LongMine** [comment]
削除処理の中でIDの整理をしているようなので重複しないようにも思えますが。
どのような場合に重複しますか？
